name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Trigger on push to the testing branch (change to main after it works)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Set up virtual environment and Install dependencies
      - name: Virtual Environment and Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (ensure virtual environment is active)
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

      # Step 5: Install Heroku CLI using curl
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      # Step 6: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/make-an-order.git
          git push heroku main  # Push testing branch to Heroku's main branch
